.test_template: &test_definition
  only:
    - master
    - devel
  script:
    - /opt/julia-1.3.1/bin/julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("OTRecod"); Pkg.test("OTRecod"; coverage = true)'


test:1.3:
  image: julia:1.3
  <<: *test_definition